
import React from 'react';
import { Button } from '@/components/ui/button';
import { Facebook, Twitter, Linkedin, Instagram, Pinterest } from 'lucide-react';
import { toast } from '@/components/ui/use-toast';

interface SocialIconsProps {
  content: string;
}

const SocialIcons: React.FC<SocialIconsProps> = ({ content }) => {
  const shareToSocial = (platform: string) => {
    if (!content) return;
    
    const encodedText = encodeURIComponent(`${content} - Generated by Pointlessly Genius`);
    let shareUrl = '';
    
    switch (platform) {
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=https://pointlessly.genius&quote=${encodedText}`;
        break;
      case 'twitter':
        shareUrl = `https://twitter.com/intent/tweet?text=${encodedText}`;
        break;
      case 'linkedin':
        shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=https://pointlessly.genius&summary=${encodedText}`;
        break;
      case 'whatsapp':
        shareUrl = `https://api.whatsapp.com/send?text=${encodedText}`;
        break;
      case 'pinterest':
        shareUrl = `https://pinterest.com/pin/create/button/?description=${encodedText}`;
        break;
      case 'instagram':
        toast({
          title: "Instagram Sharing",
          description: "Copy the text and share it on Instagram manually",
          variant: "default"
        });
        return;
    }
    
    window.open(shareUrl, '_blank');
  };

  return (
    <div className="flex flex-wrap justify-center gap-3 mt-2">
      <Button 
        variant="ghost" 
        size="icon" 
        onClick={() => shareToSocial('facebook')} 
        className="bg-blue-100 hover:bg-blue-200"
      >
        <Facebook className="h-5 w-5 text-blue-600" />
      </Button>
      <Button 
        variant="ghost" 
        size="icon" 
        onClick={() => shareToSocial('twitter')} 
        className="bg-sky-100 hover:bg-sky-200"
      >
        <Twitter className="h-5 w-5 text-sky-600" />
      </Button>
      <Button 
        variant="ghost" 
        size="icon" 
        onClick={() => shareToSocial('linkedin')} 
        className="bg-blue-100 hover:bg-blue-200"
      >
        <Linkedin className="h-5 w-5 text-blue-700" />
      </Button>
      <Button 
        variant="ghost" 
        size="icon" 
        onClick={() => shareToSocial('whatsapp')} 
        className="bg-green-100 hover:bg-green-200"
      >
        <Linkedin className="h-5 w-5 text-green-600" />
      </Button>
      <Button 
        variant="ghost" 
        size="icon" 
        onClick={() => shareToSocial('pinterest')} 
        className="bg-red-100 hover:bg-red-200"
      >
        <Pinterest className="h-5 w-5 text-red-600" />
      </Button>
      <Button 
        variant="ghost" 
        size="icon" 
        onClick={() => shareToSocial('instagram')} 
        className="bg-purple-100 hover:bg-purple-200"
      >
        <Instagram className="h-5 w-5 text-purple-600" />
      </Button>
    </div>
  );
};

export default SocialIcons;
