// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcoptfgqnyiasxicxhnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjb3B0ZmdxbnlpYXN4aWN4aG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjkzMTQsImV4cCI6MjA2MjYwNTMxNH0.ID7VhD9V-eTFvvLQULxRESy2v15eJbeNJ4ERUzJLVVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);